apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: quoteservice-service
  name: quoteservice-service
spec:
  ports:
  - name: 8080-8882
    port: 8080
    protocol: TCP
    targetPort: 8882
  selector:
    app: quoteservice-app
    tier: backend
  type: ClusterIP
status:
  loadBalancer: {}
