apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: gcr.io/gcp-playground-295112/frontservice
      jib:
        args: ['-DskipTests']
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
