apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontservice-service-lb
  name: frontservice-service-lb
spec:
  ports:
    - name: 8080-8881
      port: 8080
      protocol: TCP
      targetPort: 8881
  selector:
    app: frontservice-app
    tier: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
